apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: anuddeeph/apache-webserver-php
        volumeMounts:
        - name: my-volume1
          mountPath: /data1
        - name: my-volume2
          mountPath: /data2
        - name: my-volume3
          mountPath: /data3
        - name: my-volume4
          mountPath: /data4
        - name: my-volume5
          mountPath: /data5
        - name: my-volume6
          mountPath: /data6
      volumes:
      - name: my-volume1
        persistentVolumeClaim:
          claimName: pvc1
      - name: my-volume2
        persistentVolumeClaim:
          claimName: pvc2
      - name: my-volume3
        persistentVolumeClaim:
          claimName: pvc3
      - name: my-volume4
        persistentVolumeClaim:
          claimName: pvc4
      - name: my-volume5
        persistentVolumeClaim:
          claimName: pvc5
      - name: my-volume6
        persistentVolumeClaim:
          claimName: pvc6
